"""
生产包一体化打包器

一键生成可直接发给加工厂的完整生产数据包 (ZIP):
- STEP AP242 装配体                (.stp)
- 各零件独立 STEP                  (.stp)
- 2D 工程图纸                      (.pdf, .png)
- DXF 二维图                       (.dxf)
- 干涉检查报告                     (.json, .txt)
- 物料清单                         (.json, .csv)
- 工艺说明 README                  (.md)
- 3D 打印 STL (可选)               (.stl)
- PBR 渲染图                       (.png)
- glTF 交互模型                    (.glb)
"""

from __future__ import annotations

import csv
import datetime
import json
import os
import shutil
import zipfile
from typing import Dict, List, Optional


def generate_readme(body_data: dict, report: dict) -> str:
    """生成工艺说明 README"""
    fitness = body_data.get("fitness", 0)
    parts_count = len(body_data.get("parts", []))
    joints_count = len(body_data.get("joints", []))

    # 材料统计
    mat_counts = {}
    for p in body_data.get("parts", []):
        pt = p.get("part_type", "unknown")
        mat_counts[pt] = mat_counts.get(pt, 0) + 1

    mat_lines = "\n".join(f"| {k} | {v} |" for k, v in sorted(mat_counts.items()))

    return f"""# ForgeCraft 制造数据包

## 项目概览

| 项目 | 值 |
|---|---|
| 生成日期 | {datetime.date.today().strftime("%Y-%m-%d")} |
| 适应度 (Fitness) | {fitness:.4f} |
| 零件总数 | {parts_count} |
| 关节总数 | {joints_count} |
| 可制造性等级 | {report.get('grade', 'N/A')} |

## 零件清单

| 类型 | 数量 |
|---|---|
{mat_lines}

## 制造工艺参数

- **工艺**: FDM (熔融沉积)
- **层高**: 0.20 mm
- **喷头直径**: 0.40 mm
- **填充密度**: 20%
- **支撑结构**: 自动生成
- **材料**: 见物料清单 (BOM)

## 公差要求

- **一般公差**: ISO 2768-mK
- **轴承位**: H7/g6
- **电机安装**: H8/f7
- **固定连接**: H7/p6

## 装配说明

1. 参考爆炸视图 (`gltf/` 目录) 了解装配顺序
2. 轴承安装: 压入配合, 建议使用轴承安装工具
3. 电机法兰: M3 螺栓 + 弹簧垫圈, 扭矩 1.2 Nm
4. 碳纤维管: 结构胶粘接, 固化时间 24h
5. 弹簧预紧: 安装后压缩 3mm 预紧

## 文件清单

```
production_package/
├── step/                    # STEP AP242 文件 (SolidWorks/Fusion 导入)
│   ├── assembly.stp         #   装配体
│   └── parts/               #   各零件独立文件
├── drawings/                # 2D 工程图纸
│   ├── assembly.pdf         #   装配体 PDF
│   ├── assembly.png         #   装配体 PNG
│   ├── parts/               #   各零件图纸
│   └── dxf/                 #   DXF 二维图
├── reports/                 # 制造报告
│   ├── bom.json             #   物料清单
│   ├── bom.csv              #   物料清单 (表格)
│   ├── interference.json    #   干涉检查
│   └── interference.txt     #   干涉报告
├── renders/                 # 渲染图
│   ├── paper_normal_paper_main.png
│   ├── paper_exploded_paper_main.png
│   └── ...
├── gltf/                    # 交互式 3D 模型
│   ├── assembly.glb
│   └── assembly_exploded.glb
├── stl/                     # 3D 打印 STL
│   ├── assembly.stl
│   └── parts/
└── README.md                # 本文件
```

## 联系方式

由 ForgeCraft AI 自动生成。如需调整参数, 重新运行进化流水线。

---
*Generated by ForgeCraft — AI-driven robot morphology design*
"""


def build_production_package(
    body_data: dict,
    gen,
    output_dir: str = "production_package",
    include_stl: bool = True,
    include_dxf: bool = True,
    process: str = "FDM",
    safety_clearance_mm: float = 0.4,
) -> str:
    """构建完整生产数据包

    Args:
        body_data: 装配体数据
        gen: ParametricGenerator 实例
        output_dir: 输出目录
        include_stl: 是否包含 STL
        include_dxf: 是否包含 DXF
        process: 制造工艺
        safety_clearance_mm: 安全间隙

    Returns:
        ZIP 文件路径
    """
    from forgecraft.manufacturing.step_exporter import export_step, export_step_parts
    from forgecraft.manufacturing.drawing_generator import (
        generate_engineering_drawing, export_dxf,
    )
    from forgecraft.manufacturing.interference_checker import (
        check_interferences, generate_interference_report,
    )
    from forgecraft.geometry.pbr_renderer import render_paper_suite
    from forgecraft.geometry.gltf_scene import export_gltf
    from forgecraft.manufacturing import export_stl, _part_to_mesh

    os.makedirs(output_dir, exist_ok=True)

    pkg_name = "ForgeCraft_Manufacturing_Package"
    pkg_dir = os.path.join(output_dir, pkg_name)
    if os.path.exists(pkg_dir):
        shutil.rmtree(pkg_dir)

    # 目录结构
    dirs = {
        "step_parts": os.path.join(pkg_dir, "step", "parts"),
        "drawings_parts": os.path.join(pkg_dir, "drawings", "parts"),
        "dxf_dir": os.path.join(pkg_dir, "drawings", "dxf"),
        "reports": os.path.join(pkg_dir, "reports"),
        "renders": os.path.join(pkg_dir, "renders"),
        "gltf": os.path.join(pkg_dir, "gltf"),
        "stl_parts": os.path.join(pkg_dir, "stl", "parts"),
    }
    for d in dirs.values():
        os.makedirs(d, exist_ok=True)

    print("  Building production package...")

    # 1. STEP
    print("    [1/6] STEP AP242 export...")
    try:
        export_step(body_data, gen,
                    os.path.join(pkg_dir, "step", "assembly.stp"),
                    quality="high")
        export_step_parts(body_data, gen, dirs["step_parts"], quality="high")
    except Exception as e:
        print(f"      STEP skipped: {e}")

    # 2. 图纸
    print("    [2/6] Engineering drawings...")
    try:
        generate_engineering_drawing(body_data, gen, dirs["drawings_parts"],
                                     prefix="part", dpi=200)
        # 装配体图纸
        asm_drawing = generate_engineering_drawing(body_data, gen, pkg_dir + "/drawings",
                                                  prefix="assembly", dpi=300)
    except Exception as e:
        print(f"      Drawings skipped: {e}")

    # 3. DXF
    if include_dxf:
        print("    [3/6] DXF export...")
        try:
            export_dxf(body_data, gen, dirs["dxf_dir"])
        except Exception as e:
            print(f"      DXF skipped: {e}")
    else:
        print("    [3/6] DXF skipped (disabled)")

    # 4. STL
    if include_stl:
        print("    [4/6] STL export...")
        try:
            for p in body_data.get("parts", []):
                pt = p.get("part_type", "unknown")
                pid = p.get("part_id", "unknown")
                params = p.get("params", {})
                mesh = gen.make(pt, params)
                if mesh:
                    mesh.export(os.path.join(dirs["stl_parts"], f"{pid}.stl"))
        except Exception as e:
            print(f"      STL skipped: {e}")
    else:
        print("    [4/6] STL skipped (disabled)")

    # 5. 报告 + 干涉检查
    print("    [5/6] Reports & interference...")
    try:
        # BOM
        bom = body_data.get("bom", {})
        if not bom:
            bom = {}
            for p in body_data.get("parts", []):
                pt = p.get("part_type", "unknown")
                bom[pt] = bom.get(pt, 0) + 1

        with open(os.path.join(dirs["reports"], "bom.json"), "w") as f:
            json.dump(bom, f, indent=2)

        # BOM CSV
        with open(os.path.join(dirs["reports"], "bom.csv"), "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["PartType", "Quantity"])
            for k, v in sorted(bom.items()):
                w.writerow([k, v])

        # 干涉检查
        generate_interference_report(
            body_data, gen,
            os.path.join(dirs["reports"], "assembly"),
            process=process, safety_clearance_mm=safety_clearance_mm,
        )

        # README
        report = {"grade": body_data.get("manufacturability_grade", "A")}
        with open(os.path.join(pkg_dir, "README.md"), "w", encoding="utf-8") as f:
            f.write(generate_readme(body_data, report))
    except Exception as e:
        print(f"      Reports partially skipped: {e}")

    # 6. 渲染 + glTF
    print("    [6/6] Renders & glTF...")
    try:
        render_paper_suite(body_data, gen, dirs["renders"], prefix="paper")
    except Exception as e:
        print(f"      Renders skipped: {e}")
    try:
        export_gltf(body_data, gen, dirs["gltf"], prefix="assembly")
    except Exception as e:
        print(f"      glTF skipped: {e}")

    # ZIP
    zip_path = os.path.join(output_dir, f"{pkg_name}.zip")
    print(f"  Zipping → {zip_path}...")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs_f, files in os.walk(pkg_dir):
            for fname in files:
                full = os.path.join(root, fname)
                arcname = os.path.relpath(full, pkg_dir)
                zf.write(full, arcname)

    size_mb = os.path.getsize(zip_path) / (1024 * 1024)
    print(f"  Package: {zip_path} ({size_mb:.1f} MB)")
    return zip_path
