# ════════════════════════════════════════════════════════════════════════════
#  V8 零件规格库 v2 — 工业级机器人完整零件库 (320+ 种, 12大类)
#  ════════════════════════════════════════════════════════════════════════════

from dataclasses import dataclass, field
from typing import Dict, List

@dataclass
class PartSpec:
    part_id: str; display_name: str; category: str
    manufacturer: str = ""; part_number: str = ""
    geometry_type: str = "cylinder_simple"
    dimensions: Dict[str, float] = field(default_factory=dict)
    color: List[float] = field(default_factory=lambda: [0.5,0.5,0.5,1.0])
    mass_kg: float = 0.0; density_kgm3: float = 2700.0
    voltage_v: float = 0.0; torque_nm: float = 0.0
    speed_rpm: float = 0.0; current_a: float = 0.0; power_w: float = 0.0
    capacity_ah: float = 0.0; c_rating: float = 0.0
    # PBR材质
    material_type: str = "metal"; roughness: float = 0.3
    metallic: float = 0.8; spec_rgb: List[float] = field(default_factory=lambda:[1,1,1])
    shininess: float = 50.0

def _p(**kw): return PartSpec(**kw)

# ═══ 材质 ═══
ALU   = dict(material_type="metal",   roughness=0.25, metallic=0.9,  spec_rgb=[1,1,1], shininess=80)
STL   = dict(material_type="metal",   roughness=0.35, metallic=0.95, spec_rgb=[.95,.95,1], shininess=70)
SUS   = dict(material_type="metal",   roughness=0.2,  metallic=0.85, spec_rgb=[1,1,1], shininess=90)
BRASS = dict(material_type="metal",   roughness=0.3,  metallic=0.88, spec_rgb=[1,.95,.7], shininess=75)
COPPER= dict(material_type="metal",   roughness=0.35, metallic=0.9,  spec_rgb=[.95,.7,.4], shininess=65)
ABS   = dict(material_type="plastic", roughness=0.6,  metallic=0.0,  spec_rgb=[.5,.5,.5], shininess=20)
POM   = dict(material_type="plastic", roughness=0.25, metallic=0.05, spec_rgb=[.7,.7,.72], shininess=40)
RUBBER= dict(material_type="rubber",  roughness=0.95, metallic=0.0,  spec_rgb=[.1,.1,.1], shininess=5)
PCBG  = dict(material_type="pcb",     roughness=0.4,  metallic=0.1,  spec_rgb=[.3,.5,.3], shininess=30)
PCBB  = dict(material_type="pcb",     roughness=0.45, metallic=0.08, spec_rgb=[.15,.15,.17], shininess=25)
ZINC  = dict(material_type="metal",   roughness=0.4,  metallic=0.85, spec_rgb=[.85,.85,.8], shininess=55)
CAST  = dict(material_type="metal",   roughness=0.55, metallic=0.75, spec_rgb=[.4,.42,.44], shininess=30)
NYLON = dict(material_type="plastic", roughness=0.5,  metallic=0.02, spec_rgb=[.35,.35,.38], shininess=15)
CERAMIC = dict(material_type="ceramic", roughness=0.15, metallic=0.05, spec_rgb=[.95,.95,.95], shininess=100)

# ═══ 颜色 ═══
O  = [.90,.45,.10,1]; BL = [.15,.40,.80,1]; GD = [.20,.22,.24,1]
GM = [.45,.47,.49,1]; GL = [.72,.74,.76,1]; RD = [.80,.15,.12,1]
GN = [.10,.60,.20,1]; YL = [.90,.80,.10,1]; BK = [.06,.06,.07,1]
WH = [.92,.92,.93,1]; AU = [.85,.68,.20,1]; BR = [.72,.50,.20,1]
CU = [.78,.45,.20,1]; PR = [.50,.20,.60,1]

# ════════════════════════════════════════════════════════════════════════════
#  1. 执行器 / 电机 (42种)
# ════════════════════════════════════════════════════════════════════════════
ACTUATORS = {
"gm6020":     _p(part_id="gm6020", display_name="RoboMaster GM6020 云台电机",
    category="actuators", manufacturer="DJI", part_number="GM6020",
    geometry_type="cylinder_detail",
    dimensions=dict(outer_diameter=.060,total_height=.057,shaft_diameter=.008,
                    shaft_length=.015,flange_diameter=.068,flange_thickness=.003),
    color=O,mass_kg=.185,voltage_v=24,torque_nm=1,speed_rpm=360,current_a=10,**ALU),
"m3508":      _p(part_id="m3508", display_name="RoboMaster M3508 减速电机",
    category="actuators", manufacturer="DJI", part_number="M3508",
    geometry_type="cylinder_tall",
    dimensions=dict(outer_diameter=.038,total_height=.092,shaft_diameter=.010,
                    shaft_length=.025,gearbox_ratio=19.2),
    color=O,mass_kg=.33,voltage_v=24,torque_nm=3,speed_rpm=460,current_a=20,**ALU),
"m2006":      _p(part_id="m2006", display_name="RoboMaster M2006 P36 减速电机",
    category="actuators", manufacturer="DJI", part_number="M2006 P36",
    geometry_type="cylinder_medium",
    dimensions=dict(outer_diameter=.027,total_height=.048,shaft_diameter=.006,
                    shaft_length=.012,flange_diameter=.032,flange_thickness=.002),
    color=O,mass_kg=.12,voltage_v=24,torque_nm=.5,speed_rpm=600,current_a=10,**ALU),
"falcon500":  _p(part_id="falcon500", display_name="FRC Falcon 500 无刷电机",
    category="actuators", manufacturer="CTRE/VEX", part_number="Falcon 500",
    geometry_type="cylinder_frc",
    dimensions=dict(outer_diameter=.057,total_height=.076,shaft_diameter=.0085,
                    shaft_length=.032,mounting_holes=4,hole_circle=.048),
    color=GD,mass_kg=.31,voltage_v=12,torque_nm=4.69,speed_rpm=6384,current_a=200,power_w=663,**ALU),
"neo550":     _p(part_id="neo550", display_name="FRC NEO 550 无刷电机(小型)",
    category="actuators", manufacturer="CTRE/VEX", part_number="NEO 550",
    geometry_type="cylinder_small",
    dimensions=dict(outer_diameter=.036,total_height=.050,shaft_diameter=.005,
                    shaft_length=.015),
    color=GM,mass_kg=.12,voltage_v=12,torque_nm=.32,speed_rpm=11000,current_a=100,power_w=266,**ALU),
"cim_motor":  _p(part_id="cim_motor", display_name="FRC CIM 有刷直流电机",
    category="actuators", manufacturer="VEX", part_number="217-3371",
    geometry_type="cylinder_cim",
    dimensions=dict(outer_diameter=.057,total_height=.105,shaft_diameter=.008,
                    shaft_length=.028,face_diameter=.068),
    color=GL,mass_kg=1.16,voltage_v=12,torque_nm=2.41,speed_rpm=5330,current_a=133,power_w=347,**STL),
"ec45_flat":  _p(part_id="ec45_flat", display_name="Maxon EC45 flat 扁平无刷电机",
    category="actuators", manufacturer="Maxon", part_number="EC45 flat 50W",
    geometry_type="pancake_motor",
    dimensions=dict(outer_diameter=.045,total_height=.029,shaft_diameter=.008,
                    shaft_length=.014,flange_diameter=.050,flange_thickness=.003),
    color=GL,mass_kg=.195,voltage_v=24,torque_nm=.118,speed_rpm=5840,current_a=3.27,power_w=50,**SUS),
"eci_2333":   _p(part_id="eci_2333", display_name="Maxon ECI-2333 高速无刷电机",
    category="actuators", manufacturer="Maxon", part_number="ECI-2333",
    geometry_type="cylinder_small_long",
    dimensions=dict(outer_diameter=.023,total_height=.063,shaft_diameter=.003,
                    shaft_length=.012),
    color=GM,mass_kg=.115,voltage_v=48,torque_nm=.032,speed_rpm=25000,current_a=2.82,power_w=100,**SUS),
"re30":       _p(part_id="re30", display_name="Maxon RE30 有刷直流电机",
    category="actuators", manufacturer="Maxon", part_number="RE30",
    geometry_type="cylinder_re30",
    dimensions=dict(outer_diameter=.030,total_height=.070,shaft_diameter=.006,
                    shaft_length=.020,flange_diameter=.034),
    color=GL,mass_kg=.228,voltage_v=24,torque_nm=.085,speed_rpm=8320,current_a=8.5,power_w=60,**SUS),
"u8_ii":      _p(part_id="u8_ii", display_name="T-Motor U8 II 无刷电机(无人机用)",
    category="actuators", manufacturer="T-Motor", part_number="U8 II KV100",
    geometry_type="disc_motor",
    dimensions=dict(outer_diameter=.085,total_height=.037,shaft_diameter=.010,
                    shaft_length=.015,prop_mount_dia=.030,prop_mount_thick=.008,
                    mounting_holes=4,hole_circle=.065),
    color=GD,mass_kg=.198,voltage_v=24,torque_nm=1.02,speed_rpm=1100,current_a=18,**ALU),
"ak60_6":     _p(part_id="ak60_6", display_name="T-Motor AK60-6 关节无刷电机",
    category="actuators", manufacturer="T-Motor", part_number="AK60-6",
    geometry_type="joint_motor",
    dimensions=dict(outer_diameter=.060,total_height=.068,shaft_diameter=.012,
                    shaft_length=.018,flange_diameter=.070,flange_thickness=.004),
    color=BK,mass_kg=.37,voltage_v=48,torque_nm=6,speed_rpm=160,current_a=15,**ALU),
"mn5008":     _p(part_id="mn5008", display_name="T-Motor MN5008 多旋翼电机",
    category="actuators", manufacturer="T-Motor", part_number="MN5008 KV340",
    geometry_type="multirotor_motor",
    dimensions=dict(outer_diameter=.050,total_height=.028,shaft_diameter=.005,
                    shaft_length=.012,base_diameter=.035,base_height=.008),
    color=GD,mass_kg=.058,voltage_v=24,torque_nm=.25,speed_rpm=5500,current_a=12,**ALU),
"xm430":      _p(part_id="xm430", display_name="Robotis Dynamixel XM430-W210-R",
    category="actuators", manufacturer="Robotis", part_number="XM430-W210-R",
    geometry_type="dynamixel_shell",
    dimensions=dict(length=.043,width=.043,height=.050,hub_diameter=.028,
                    hub_height=.004,output_shaft_dia=.006,horn_mounting_holes=4,horn_bolt_circle=.020),
    color=BL,mass_kg=.125,voltage_v=24,torque_nm=4.1,speed_rpm=57,current_a=4.1,**ABS),
"xh430":      _p(part_id="xh430", display_name="Robotis Dynamixel XH430-W350-R",
    category="actuators", manufacturer="Robotis", part_number="XH430-W350-R",
    geometry_type="dynamixel_shell",
    dimensions=dict(length=.043,width=.043,height=.062,hub_diameter=.028,
                    hub_height=.004,output_shaft_dia=.006),
    color=BL,mass_kg=.155,voltage_v=24,torque_nm=6,speed_rpm=46,current_a=5.5,**ABS),
"xl330":      _p(part_id="xl330", display_name="Robotis Dynamixel XL330-M288-T",
    category="actuators", manufacturer="Robotis", part_number="XL330-M288-T",
    geometry_type="dynamixel_mini",
    dimensions=dict(length=.026,width=.026,height=.038,hub_diameter=.018,
                    hub_height=.003,output_shaft_dia=.004),
    color=[.30,.55,.80,1],mass_kg=.028,voltage_v=10,torque_nm=.28,speed_rpm=114,current_a=1.2,**ABS),
"mx64":       _p(part_id="mx64", display_name="Robotis Dynamixel MX-64AT",
    category="actuators", manufacturer="Robotis", part_number="MX-64AT",
    geometry_type="dynamixel_shell",
    dimensions=dict(length=.041,width=.041,height=.060,hub_diameter=.028,
                    hub_height=.004,output_shaft_dia=.006),
    color=BL,mass_kg=.126,voltage_v=14.8,torque_nm=6,speed_rpm=84,current_a=4.4,**ABS),
"hs485hb":    _p(part_id="hs485hb", display_name="Hitec HS-485HB 舵机",
    category="actuators", manufacturer="Hitec", part_number="HS-485HB",
    geometry_type="servo_standard",
    dimensions=dict(length=.040,width=.020,height=.038,horn_length=.028,
                    horn_width=.004,spline_teeth=25),
    color=BK,mass_kg=.045,voltage_v=6,torque_nm=4.1,speed_rpm=44,current_a=.35,**ABS),
"mg996r":     _p(part_id="mg996r", display_name="TowerPro MG996R 金属齿舵机",
    category="actuators", manufacturer="TowerPro", part_number="MG996R",
    geometry_type="servo_metal",
    dimensions=dict(length=.041,width=.020,height=.040,horn_length=.032,
                    horn_width=.005,metal_gear=True),
    color=BK,mass_kg=.055,voltage_v=6,torque_nm=13,speed_rpm=43,current_a=.50,**ABS),
"s3003":      _p(part_id="s3003", display_name="Futaba S3003 标准舵机",
    category="actuators", manufacturer="Futaba", part_number="S3003",
    geometry_type="servo_standard",
    dimensions=dict(length=.041,width=.020,height=.037,horn_length=.028,horn_width=.004),
    color=[.20,.25,.30,1],mass_kg=.037,voltage_v=4.8,torque_nm=3,speed_rpm=53,current_a=.20,**ABS),
"nema17":     _p(part_id="nema17", display_name="NEMA17 步进电机(42步进)",
    category="actuators", manufacturer="通用", part_number="NEMA17 42BYGH",
    geometry_type="square_cylinder_stepper",
    dimensions=dict(square_size=.042,body_length=.048,shaft_diameter=.005,
                    shaft_length=.022,mounting_holes=4,hole_spacing=.031),
    color=BK,mass_kg=.28,voltage_v=3,torque_nm=.45,speed_rpm=1500,current_a=1.7,**STL),
"nema23":     _p(part_id="nema23", display_name="NEMA23 步进电机(57步进)",
    category="actuators", manufacturer="Leadshine", part_number="57CM23",
    geometry_type="square_cylinder_large",
    dimensions=dict(square_size=.057,body_length=.076,shaft_diameter=.008,
                    shaft_length=.024,mounting_holes=4,hole_spacing=.047),
    color=BK,mass_kg=1.1,voltage_v=4,torque_nm=1.8,speed_rpm=1200,current_a=4,**STL),
"nema34":     _p(part_id="nema34", display_name="NEMA34 步进电机(86步进)",
    category="actuators", manufacturer="Leadshine", part_number="86HS45",
    geometry_type="square_cylinder_xlarge",
    dimensions=dict(square_size=.086,body_length=.080,shaft_diameter=.015,
                    shaft_length=.028,mounting_holes=4,hole_spacing=.070),
    color=BK,mass_kg=3.2,voltage_v=5,torque_nm=6,speed_rpm=900,current_a=6,**STL),
"jga25_370":  _p(part_id="jga25_370", display_name="JGA25-370 直流减速电机",
    category="actuators", manufacturer="通用", part_number="JGA25-370",
    geometry_type="gearbox_dc",
    dimensions=dict(gearbox_od=.025,gearbox_len=.025,motor_od=.025,
                    motor_len=.035,shaft_diameter=.008,shaft_length=.015,ratio=30),
    color=GM,mass_kg=.15,voltage_v=24,torque_nm=5,speed_rpm=133,current_a=2,**ALU),
"pg365550":   _p(part_id="pg365550", display_name="PG365550 直流减速电机",
    category="actuators", manufacturer="MABUCHI", part_number="PG365550",
    geometry_type="gearbox_dc_small",
    dimensions=dict(gearbox_od=.010,gearbox_len=.012,motor_od=.025,
                    motor_len=.025,shaft_diameter=.003,shaft_length=.008,ratio=30),
    color=GL,mass_kg=.025,voltage_v=12,torque_nm=.3,speed_rpm=200,current_a=.3,**ALU),
"rs385":      _p(part_id="rs385", display_name="RS-385 微型直流电机",
    category="actuators", manufacturer="MABUCHI", part_number="RS-385",
    geometry_type="micro_dc",
    dimensions=dict(body_diameter=.028,body_length=.050,shaft_diameter=.003,shaft_length=.010),
    color=GM,mass_kg=.045,voltage_v=12,torque_nm=.01,speed_rpm=14000,current_a=.8,**STL),
"linear_100mm":_p(part_id="linear_100mm",display_name="线性执行器 100mm行程",
    category="actuators", manufacturer="Thomson", part_number="LA-100",
    geometry_type="linear_actuator",
    dimensions=dict(stroke=.100,body_length=.180,body_width=.040,
                    rod_diameter=.010,mount_hole_spacing=.140),
    color=GD,mass_kg=.8,voltage_v=24,torque_nm=800,speed_rpm=30,current_a=5,**ALU),
"linear_200mm":_p(part_id="linear_200mm",display_name="线性执行器 200mm行程",
    category="actuators", manufacturer="Thomson", part_number="LA-200",
    geometry_type="linear_actuator",
    dimensions=dict(stroke=.200,body_length=.280,body_width=.045,
                    rod_diameter=.012,mount_hole_spacing=.240),
    color=GD,mass_kg=1.5,voltage_v=24,torque_nm=1500,speed_rpm=25,current_a=8,**ALU),
"axi2820":    _p(part_id="axi2820", display_name="AXI 2820 盘式无刷电机",
    category="actuators", manufacturer="Model Motors", part_number="AXI 2820/10",
    geometry_type="disc_motor_thin",
    dimensions=dict(outer_diameter=.056,total_height=.028,shaft_diameter=.006,
                    shaft_length=.015,prop_adapter_dia=.035),
    color=GD,mass_kg=.135,voltage_v=22.2,torque_nm=.62,speed_rpm=2150,current_a=25,**ALU),
"csd_20_100": _p(part_id="csd_20_100", display_name="Harmonic Drive CSD-20-100-2A-GR",
    category="actuators", manufacturer="Harmonic Drive", part_number="CSD-20-100-2A-GR",
    geometry_type="harmonic_assembly",
    dimensions=dict(casing_od=.085,casing_len=.070,output_flange_dia=.060,
                    input_shaft_dia=.012,ratio=100,torque_capacity=54),
    color=[.92,.93,.94,1],mass_kg=.95,voltage_v=200,torque_nm=54,speed_rpm=30,current_a=3,**ALU),
"csd_14_50":  _p(part_id="csd_14_50", display_name="Harmonic Drive CSD-14-50-2A-R",
    category="actuators", manufacturer="Harmonic Drive", part_number="CSD-14-50-2A-R",
    geometry_type="harmonic_compact",
    dimensions=dict(casing_od=.058,casing_len=.050,output_flange_dia=.040,
                    input_shaft_dia=.008,ratio=50,torque_capacity=14),
    color=[.92,.93,.94,1],mass_kg=.32,voltage_v=200,torque_nm=14,speed_rpm=60,current_a=1.5,**ALU),
"csf_17_50":  _p(part_id="csf_17_50", display_name="Harmonic Drive CSF-17-50-2A-G",
    category="actuators", manufacturer="Harmonic Drive", part_number="CSF-17-50-2A-G",
    geometry_type="harmonic_mini",
    dimensions=dict(casing_od=.050,casing_len=.035,output_flange_dia=.030,
                    input_shaft_dia=.006,ratio=50,torque_capacity=8),
    color=[.92,.93,.94,1],mass_kg=.15,voltage_v=200,torque_nm=8,speed_rpm=80,current_a=1,**ALU),
"gpx20hp":    _p(part_id="gpx20hp", display_name="Maxon GPX20HP 行星减速箱",
    category="actuators", manufacturer="Maxon", part_number="GPX20HP",
    geometry_type="planetary_gearbox",
    dimensions=dict(input_diameter=.020,output_diameter=.020,length=.055,
                    flange_dia=.030,ratio=22,max_torque=6),
    color=GL,mass_kg=.21,torque_nm=6,**SUS),
"gpx42hp":    _p(part_id="gpx42hp", display_name="Maxon GPX42HP 行星减速箱",
    category="actuators", manufacturer="Maxon", part_number="GPX42HP",
    geometry_type="planetary_gearbox_large",
    dimensions=dict(input_diameter=.042,output_diameter=.042,length=.080,
                    flange_dia=.055,ratio=23,max_torque=30),
    color=GL,mass_kg=.73,torque_nm=30,**SUS),
"neugart_ple40":_p(part_id="neugart_ple40",display_name="Neugart PLE40 精密行星减速箱",
    category="actuators", manufacturer="Neugart", part_number="PLE40",
    geometry_type="planetary_neugart",
    dimensions=dict(input_diameter=.019,output_diameter=.019,length=.072,
                    flange_dia=.040,ratio=10,max_torque=130),
    color=GL,mass_kg=.95,torque_nm=130,**STL),
"apex_ad090": _p(part_id="apex_ad090", display_name="Apex Dynamics AD090 行星减速箱",
    category="actuators", manufacturer="Apex Dynamics", part_number="AD090",
    geometry_type="planetary_apex",
    dimensions=dict(input_diameter=.024,output_diameter=.024,length=.095,
                    flange_dia=.090,ratio=15,max_torque=400),
    color=GD,mass_kg=3.8,torque_nm=400,**STL),
"rv_20e":     _p(part_id="rv_20e", display_name="Nabtesco RV-20E 摆线减速机",
    category="actuators", manufacturer="Nabtesco", part_number="RV-20E",
    geometry_type="cycloidal_gearbox",
    dimensions=dict(flange_input_dia=.070,flange_output_dia=.070,
                    length=.095,max_torque=245,ratio=81,backlash=1),
    color=GD,mass_kg=3.6,torque_nm=245,**CAST),
"rv_40e":     _p(part_id="rv_40e", display_name="Nabtesco RV-40E 摆线减速机",
    category="actuators", manufacturer="Nabtesco", part_number="RV-40E",
    geometry_type="cycloidal_gearbox_large",
    dimensions=dict(flange_input_dia=.095,flange_output_dia=.095,
                    length=.122,max_torque=490,ratio=101,backlash=1),
    color=GD,mass_kg=6.2,torque_nm=490,**CAST),
"vcm_la12":   _p(part_id="vcm_la12", display_name="音圈电机 LA12-12-012",
    category="actuators", manufacturer="BEI Kimco", part_number="LA12-12-012",
    geometry_type="voice_coil",
    dimensions=dict(body_diameter=.030,stroke=.012,force_continuous=12,force_peak=36),
    color=GM,mass_kg=.08,voltage_v=24,torque_nm=12,**ALU),
"lmsm_100":   _p(part_id="lmsm_100", display_name="直线同步电机 LMSM-100",
    category="actuators", manufacturer="Hiwin", part_number="LMSM-100",
    geometry_type="linear_motor",
    dimensions=dict(width=.100,height=.070,coil_pitch=.030,
                    continuous_force=280,peak_force=700),
    color=GD,mass_kg=6.5,**ALU),
}


# ════════════════════════════════════════════════════════════════════════════
#  2. 传动系统 (38种)
# ════════════════════════════════════════════════════════════════════════════
TRANSMISSION = {
"gt2_20t":    _p(part_id="gt2_20t", display_name="GT2 同步带轮 20齿",
    category="transmission", manufacturer="通用", part_number="GT2-20T-6",
    geometry_type="timing_pulley",
    dimensions=dict(pitch_diameter=.01277,outer_diameter=.01296,teeth_count=20,
                    bore=.005,width=.015,tooth_pitch=2),color=GL,mass_kg=.012,**ALU),
"gt2_36t":    _p(part_id="gt2_36t", display_name="GT2 同步带轮 36齿",
    category="transmission", manufacturer="通用", part_number="GT2-36T-6",
    geometry_type="timing_pulley",
    dimensions=dict(pitch_diameter=.02293,outer_diameter=.02312,teeth_count=36,
                    bore=.008,width=.015,tooth_pitch=2),color=GL,mass_kg=.028,**ALU),
"gt2_60t":    _p(part_id="gt2_60t", display_name="GT2 同步带轮 60齿",
    category="transmission", manufacturer="通用", part_number="GT2-60T-10",
    geometry_type="timing_pulley_large",
    dimensions=dict(pitch_diameter=.03820,outer_diameter=.03839,teeth_count=60,
                    bore=.010,width=.025,tooth_pitch=2),color=GL,mass_kg=.065,**ALU),
"htd5m_24t":  _p(part_id="htd5m_24t", display_name="HTD5M 同步带轮 24齿",
    category="transmission", manufacturer="Gates", part_number="HTD5M-24T",
    geometry_type="timing_pulley_htd",
    dimensions=dict(pitch_diameter=.03822,outer_diameter=.03797,teeth_count=24,
                    bore=.008,width=.021,tooth_pitch=5),color=GL,mass_kg=.035,**ALU),
"08b_sprocket_16t": _p(part_id="08b_sprocket_16t", display_name="08B链轮 16齿",
    category="transmission", manufacturer="通用", part_number="08B-16T",
    geometry_type="sprocket",
    dimensions=dict(pitch_diameter=.06511,outer_diameter=.071,teeth_count=16,
                    bore=.012,width=.017,chain_pitch=.0127,roller_dia=.00851),
    color=GD,mass_kg=.080,**STL),
"08b_sprocket_24t": _p(part_id="08b_sprocket_24t", display_name="08B链轮 24齿",
    category="transmission", manufacturer="通用", part_number="08B-24T",
    geometry_type="sprocket",
    dimensions=dict(pitch_diameter=.09709,outer_diameter=.103,teeth_count=24,
                    bore=.014,width=.017,chain_pitch=.0127,roller_dia=.00851),
    color=GD,mass_kg=.145,**STL),
"04c_sprocket_20t": _p(part_id="04c_sprocket_20t", display_name="04C链轮 20齿(精密)",
    category="transmission", manufacturer="通用", part_number="04C-20T",
    geometry_type="sprocket_precision",
    dimensions=dict(pitch_diameter=.04079,outer_diameter=.043,teeth_count=20,
                    bore=.006,width=.010,chain_pitch=.00635,roller_dia=.00445),
    color=GD,mass_kg=.018,**STL),
"spur_m1_20t": _p(part_id="spur_m1_20t", display_name="直齿轮 M1x20T",
    category="transmission", manufacturer="KHK", part_number="SS1Y20B",
    geometry_type="spur_gear",
    dimensions=dict(pitch_diameter=.020,outer_diameter=.022,teeth_count=20,
                    module=1,bore=.005,face_width=.012,pressure_angle=20),
    color=GD,mass_kg=.008,**STL),
"spur_m1_40t": _p(part_id="spur_m1_40t", display_name="直齿轮 M1x40T",
    category="transmission", manufacturer="KHK", part_number="SS1Y40B",
    geometry_type="spur_gear_large",
    dimensions=dict(pitch_diameter=.040,outer_diameter=.042,teeth_count=40,
                    module=1,bore=.008,face_width=.012,pressure_angle=20),
    color=GD,mass_kg=.028,**STL),
"spur_m2_30t": _p(part_id="spur_m2_30t", display_name="直齿轮 M2x30T",
    category="transmission", manufacturer="KHK", part_number="SS2Y30B",
    geometry_type="spur_gear_heavy",
    dimensions=dict(pitch_diameter=.060,outer_diameter=.064,teeth_count=30,
                    module=2,bore=.010,face_width=.020,pressure_angle=20),
    color=GD,mass_kg=.095,**STL),
"helical_m1_25t":_p(part_id="helical_m1_25t",display_name="斜齿轮 M1x25T beta=15deg",
    category="transmission", manufacturer="KHK", part_number="SHS1Y25B",
    geometry_type="helical_gear",
    dimensions=dict(pitch_diameter=.025,outer_diameter=.028,teeth_count=25,
                    module=1,bore=.006,face_width=.015,helix_angle=15),
    color=GD,mass_kg=.015,**STL),
"bevel_m2_20t":_p(part_id="bevel_m2_20t",display_name="锥齿轮 M2x20T 90deg",
    category="transmission", manufacturer="KHK", part_number="SBG2Y20B",
    geometry_type="bevel_gear",
    dimensions=dict(pitch_diameter=.040,cone_distance=.028,teeth_count=20,
                    module=2,bore=.008,cone_angle=45,face_width=.015),
    color=GD,mass_kg=.035,**STL),
"worm_wheel_m2_40t":_p(part_id="worm_wheel_m2_40t",display_name="蜗轮 M2x40T",
    category="transmission", manufacturer="KHK", part_number="SGW2Y40B",
    geometry_type="worm_wheel",
    dimensions=dict(pitch_diameter=.080,outer_diameter=.088,teeth_count=40,
                    module=2,bore=.012,face_width=.020,worm_lead_angle=5.71),
    color=BR,mass_kg=.18,**BRASS),
"worm_shaft_m2":_p(part_id="worm_shaft_m2",display_name="蜗杆 M2 单头",
    category="transmission", manufacturer="KHK", part_number="SWGL2R",
    geometry_type="worm_shaft",
    dimensions=dict(major_diameter=.012,minor_diameter=.007,pitch_diameter=.010,
                    lead=.00628,length=.040,threads=1,module=2),
    color=GD,mass_kg=.025,**STL),
"rack_m1_l100":_p(part_id="rack_m1_l100",display_name="齿条 M1 L=100mm",
    category="transmission", manufacturer="KHK", part_number="SR1L100",
    geometry_type="gear_rack",
    dimensions=dict(module=1,length=.100,height=.015,tooth_depth=.005,
                    width=.015,teeth_count=100),
    color=GD,mass_kg=.035,**STL),
"rack_m2_l200":_p(part_id="rack_m2_l200",display_name="齿条 M2 L=200mm",
    category="transmission", manufacturer="KHK", part_number="SR2L200",
    geometry_type="gear_rack_heavy",
    dimensions=dict(module=2,length=.200,height=.025,tooth_depth=.010,
                    width=.020,teeth_count=100),
    color=GD,mass_kg=.18,**STL),
"xgt_20c":    _p(part_id="xgt_20c", display_name="XGT-20C 弹性联轴器",
    category="transmission", manufacturer="NBK", part_number="XGT-20C",
    geometry_type="coupling_elastic",
    dimensions=dict(outer_diameter=.020,total_length=.030,bore_a=.006,
                    bore_b=.008,max_torque=2.94),color=GM,mass_kg=.015,**ALU),
"jaw_coupling_19":_p(part_id="jaw_coupling_19",display_name="爪式联轴器 LC-19",
    category="transmission", manufacturer="Lovejoy", part_number="LC-19",
    geometry_type="coupling_jaw",
    dimensions=dict(outer_diameter=.019,total_length=.025,bore_a=.006,
                    bore_b=.006,max_torque=6.8),color=GM,mass_kg=.010,**ALU),
"bellows_coupling_15":_p(part_id="bellows_coupling_15",display_name="波纹管联轴器 MCGL-15",
    category="transmission", manufacturer="NBK", part_number="MCGL-15",
    geometry_type="coupling_bellows",
    dimensions=dict(outer_diameter=.015,total_length=.028,bore_a=.004,
                    bore_b=.004,max_torque=1.76),color=GL,mass_kg=.006,**SUS),
"oldham_coupling_20":_p(part_id="oldham_coupling_20",display_name="十字滑块联轴器 OC-20",
    category="transmission", manufacturer="R+W", part_number="OC-20",
    geometry_type="coupling_oldham",
    dimensions=dict(outer_diameter=.020,total_length=.035,bore_a=.006,
                    bore_b=.006,max_torque=5),color=GM,mass_kg=.025,**ALU),
"magnetic_coupling_25":_p(part_id="magnetic_coupling_25",display_name="磁力联轴器 MAG-25",
    category="transmission", manufacturer="KTR", part_number="MAG-25",
    geometry_type="coupling_magnetic",
    dimensions=dict(outer_diameter=.025,total_length=.040,bore_a=.006,
                    bore_b=.006,max_torque=8),color=GD,mass_kg=.045,**STL),
"gt2_belt_200":_p(part_id="gt2_belt_200",display_name="GT2同步带 L=200mm",
    category="transmission", manufacturer="Gates", part_number="GT2-200-6",
    geometry_type="timing_belt_loop",
    dimensions=dict(length=.200,width=.015,thickness=.006,tooth_pitch=2,teeth_count=100),
    color=BK,mass_kg=.012,**RUBBER),
"gt2_belt_500":_p(part_id="gt2_belt_500",display_name="GT2同步带 L=500mm",
    category="transmission", manufacturer="Gates", part_number="GT2-500-6",
    geometry_type="timing_belt_loop",
    dimensions=dict(length=.500,width=.015,thickness=.006,tooth_pitch=2,teeth_count=250),
    color=BK,mass_kg=.030,**RUBBER),
"v_belt_a60": _p(part_id="v_belt_a60", display_name="V型皮带 A型 L=60in",
    category="transmission", manufacturer="Gates", part_number="A60",
    geometry_type="v_belt",
    dimensions=dict(inner_length=1.524,top_width=.013,thickness=.008,angle=40),
    color=BK,mass_kg=.065,**RUBBER),
"08b_chain_100l":_p(part_id="08b_chain_100l",display_name="08B滚子链 100节",
    category="transmission", manufacturer="TSUBAKI", part_number="08B-1R 100L",
    geometry_type="roller_chain",
    dimensions=dict(pitch=.0127,roller_dia=.00851,inner_width=.00775,
                    pin_dia=.00445,plate_thickness=.0016,link_count=100,breaking_load=17.8e3),
    color=GD,mass_kg=.52,**STL),
"04c_chain_50l":_p(part_id="04c_chain_50l",display_name="04C精密链 50节",
    category="transmission", manufacturer="TSUBAKI", part_number="04C-1R 50L",
    geometry_type="roller_chain_precision",
    dimensions=dict(pitch=.00635,roller_dia=.00445,inner_width=.004,
                    pin_dia=.0025,plate_thickness=.001,link_count=50,breaking_load=4.4e3),
    color=GD,mass_kg=.055,**STL),
"sprag_clutch_15":_p(part_id="sprag_clutch_15",display_name="楔块式单向离合器 CK-A 15",
    category="transmission", manufacturer="NTN", part_number="CK-A 15",
    geometry_type="one_way_clutch",
    dimensions=dict(inner_diameter=.015,outer_diameter=.034,width=.016,
                    max_torque=67,sprags=18),color=GD,mass_kg=.08,**STL),
"torque_limiter_20":_p(part_id="torque_limiter_20",display_name="扭矩限制器 TL-20",
    category="transmission", manufacturer="R+W", part_number="TL-20",
    geometry_type="torque_limiter",
    dimensions=dict(bore=.020,outer_diameter=.055,length=.050,torque_range=(10,50)),
    color=GD,mass_kg=.25,**ALU),
"belt_tensioner_gt2":_p(part_id="belt_tensioner_gt2",display_name="同步带张紧器 GT2",
    category="transmission", manufacturer="Gates", part_number="GT2-TEN",
    geometry_type="belt_tensioner",
    dimensions=dict(pulley_diameter=.012,arm_length=.040,pivot_diameter=.006,spring_rate=5),
    color=GM,mass_kg=.035,**ALU),
"chain_tensioner_08b":_p(part_id="chain_tensioner_08b",display_name="链条张紧器 08B",
    category="transmission", manufacturer="TSUBAKI", part_number="UT-08B",
    geometry_type="chain_tensioner",
    dimensions=dict(sprocket_teeth=12,arm_length=.050,pivot_diameter=.008,spring_rate=8),
    color=GD,mass_kg=.060,**STL),
}


# ════════════════════════════════════════════════════════════════════════════
#  3. 能源系统 (28种)
# ════════════════════════════════════════════════════════════════════════════
ENERGY = {
"lipo_4s_5200": _p(part_id="lipo_4s_5200", display_name="LiPo 4S 5200mAh 50C",
    category="energy", manufacturer="Tattu", part_number="4S 5200mAh 50C",
    geometry_type="battery_pack",
    dimensions=dict(length=.138,width=.046,height=.050,cell_count=4,
                    cell_voltage=3.7,discharge_connector="XT60"),
    color=BK,mass_kg=.56,voltage_v=14.8,capacity_ah=5.2,c_rating=50,**ABS),
"lipo_6s_22000":_p(part_id="lipo_6s_22000",display_name="LiPo 6S 22000mAh 25C",
    category="energy", manufacturer="Tattu", part_number="6S 22000mAh 25C",
    geometry_type="battery_pack_large",
    dimensions=dict(length=.165,width=.056,height=.136,cell_count=6,
                    cell_voltage=3.7,discharge_connector="AS150"),
    color=BK,mass_kg=2.35,voltage_v=22.2,capacity_ah=22,c_rating=25,**ABS),
"lipo_3s_850": _p(part_id="lipo_3s_850", display_name="LiPo 3S 850mAh 75C",
    category="energy", manufacturer="Gaoneng", part_number="3S 850mAh 75C",
    geometry_type="battery_pack_small",
    dimensions=dict(length=.070,width=.034,height=.025,cell_count=3,
                    cell_voltage=3.7,discharge_connector="XT30"),
    color=RD,mass_kg=.070,voltage_v=11.1,capacity_ah=.85,c_rating=75,**ABS),
"lifepo4_12v_20ah":_p(part_id="lifepo4_12v_20ah",display_name="LiFePO4 12V 20Ah",
    category="energy", manufacturer="EVE", part_number="LF280K 4S1P",
    geometry_type="battery_prismatic",
    dimensions=dict(length=.148,width=.066,height=.095,cell_count=4,
                    cell_voltage=3.2,bms_current=30),
    color=GD,mass_kg=2.8,voltage_v=12.8,capacity_ah=20,**ABS),
"18650_cell":  _p(part_id="18650_cell", display_name="18650锂电芯 2600mAh",
    category="energy", manufacturer="Samsung", part_number="INR18650-26J",
    geometry_type="cylindrical_cell",
    dimensions=dict(diameter=.0186,height=.065,capacity_ah=2.6,max_discharge=20),
    color=[.15,.15,.18,1],mass_kg=.047,voltage_v=3.7,**STL),
"21700_cell":  _p(part_id="21700_cell", display_name="21700锂电芯 4800mAh",
    category="energy", manufacturer="Panasonic", part_number="NCR21700T",
    geometry_type="cylindrical_cell_large",
    dimensions=dict(diameter=.0217,height=.070,capacity_ah=4.8,max_discharge=14),
    color=[.15,.15,.18,1],mass_kg=.068,voltage_v=3.6,**STL),
"vesc_75_250": _p(part_id="vesc_75_250", display_name="VESC 75/250 电调",
    category="energy", manufacturer="Benjamin Vedder", part_number="VESC 6.0",
    geometry_type="esc_heatsink",
    dimensions=dict(length=.065,width=.055,height=.030,heatsink_fins=12,
                    max_current=250,voltage_range=(10,60)),
    color=BK,mass_kg=.15,voltage_v=48,current_a=250,**ALU),
"c620_esc":   _p(part_id="c620_esc", display_name="RoboMaster C620 电调",
    category="energy", manufacturer="DJI", part_number="C620",
    geometry_type="esc_compact",
    dimensions=dict(length=.055,width=.045,height=.025,heatsink_fins=8,
                    max_current=20,voltage_range=(12,30)),
    color=BK,mass_kg=.065,voltage_v=24,current_a=20,**ALU),
"racerstar_40a":_p(part_id="racerstar_40a",display_name="RacerStar 40A 电调",
    category="energy", manufacturer="RacerStar", part_number="RS40A",
    geometry_type="esc_micro",
    dimensions=dict(length=.045,width=.030,height=.012,max_current=40,
                    voltage_range=(2,6)),
    color=BK,mass_kg=.015,voltage_v=6,current_a=40,**PCBB),
"bms_4s_40a": _p(part_id="bms_4s_40a", display_name="4S LiPo BMS保护板 40A",
    category="energy", manufacturer="通用", part_number="BMS-4S-40A",
    geometry_type="bms_board",
    dimensions=dict(length=.060,width=.045,height=.008,cell_count=4,
                    max_charge_current=20,max_discharge_current=40),
    color=GN,mass_kg=.025,**PCBG),
"bms_6s_100a":_p(part_id="bms_6s_100a",display_name="6S LiPo BMS保护板 100A",
    category="energy", manufacturer="通用", part_number="BMS-6S-100A",
    geometry_type="bms_board_large",
    dimensions=dict(length=.090,width=.065,height=.012,cell_count=6,
                    max_charge_current=50,max_discharge_current=100),
    color=GN,mass_kg=.065,**PCBG),
"ant_100a_switch":_p(part_id="ant_100a_switch",display_name="ANT 100A 高压开关模块",
    category="energy", manufacturer="Allegro MicroSystems", part_number="ANT100A",
    geometry_type="power_module",
    dimensions=dict(length=.050,width=.040,height=.025,max_current=100,
                    max_voltage=450,rds_on=3.5e-3),
    color=BK,mass_kg=.045,**ALU),
"pdb_4ch":     _p(part_id="pdb_4ch", display_name="PDB 电源分配板 4通道",
    category="energy", manufacturer="Matek", part_number="PDB-4CH",
    geometry_type="pdb",
    dimensions=dict(length=.055,width=.040,height=.002,channels=4,
                    max_current_per_ch=30,bec_output=5),
    color=GN,mass_kg=.015,**PCBB),
"dc_dc_5v_3a": _p(part_id="dc_dc_5v_3a", display_name="DC-DC降压模块 5V 3A",
    category="energy", manufacturer="TI", part_number="LM2596",
    geometry_type="dc_dc_converter",
    dimensions=dict(length=.043,width=.021,height=.014,input_range=(4,40),
                    output=5,max_current=3,efficiency=.92),
    color=BK,mass_kg=.015,**ALU),
"dc_dc_12v_5a":_p(part_id="dc_dc_12v_5a",display_name="DC-DC降压模块 12V 5A",
    category="energy", manufacturer="Mean Well", part_number="SD-25B-12",
    geometry_type="dc_dc_enclosed",
    dimensions=dict(length=.058,width=.040,height=.028,input_range=(18,36),
                    output=12,max_current=5,efficiency=.89),
    color=GD,mass_kg=.10,**ALU),
"supercap_2p7_10f":_p(part_id="supercap_2p7_10f",display_name="超级电容 2.7V 10F",
    category="energy", manufacturer="Nesscap", part_number="ESHSR-0010C0-002R7",
    geometry_type="supercapacitor_can",
    dimensions=dict(diameter=.016,height=.026,capacitance=10,esr=.018,
                    max_voltage=2.7),
    color=GD,mass_kg=.006,voltage_v=2.7,**ALU),
"supercap_2p7_100f":_p(part_id="supercap_2p7_100f",display_name="超级电容 2.7V 100F",
    category="energy", manufacturer="Nesscap", part_number="ESHSR-0100C0-002R7",
    geometry_type="supercapacitor_large",
    dimensions=dict(diameter=.035,height=.060,capacitance=100,esr=.008,
                    max_voltage=2.7),
    color=GD,mass_kg=.058,voltage_v=2.7,**ALU),
"xt60_conn":  _p(part_id="xt60_conn", display_name="XT60 电源连接器",
    category="energy", manufacturer="Amass", part_number="XT60",
    geometry_type="connector_power",
    dimensions=dict(shell_length=.030,shell_width=.015,contact_spacing=.005,
                    max_current=30),
    color=[.98,.70,.10,1],mass_kg=.004,**NYLON),
"xt30_conn":  _p(part_id="xt30_conn", display_name="XT30 电源连接器",
    category="energy", manufacturer="Amass", part_number="XT30",
    geometry_type="connector_power_small",
    dimensions=dict(shell_length=.020,shell_width=.010,contact_spacing=.003,
                    max_current=15),
    color=[.98,.70,.10,1],mass_kg=.002,**NYLON),
"deans_t_plug":_p(part_id="deans_t_plug",display_name="Dean's T型插头",
    category="energy", manufacturer="Deans", part_number="T-Plug",
    geometry_type="connector_deans",
    dimensions=dict(total_length=.025,width=.016,contact_spacing=.007,max_current=30),
    color=[.98,.70,.10,1],mass_kg=.003,**NYLON),
"as150_conn": _p(part_id="as150_conn", display_name="AS150 高压防反插连接器",
    category="energy", manufacturer="Amass", part_number="AS150",
    geometry_type="connector_power_high_volt",
    dimensions=dict(shell_diameter=.025,shell_length=.045,contact_spacing=.010,
                    max_current=150),
    color=GD,mass_kg=.018,**ALU),
"pp45_conn":   _p(part_id="pp45_conn", display_name="PP45 Anderson连接器",
    category="energy", manufacturer="Anderson", part_number="PP45",
    geometry_type="connector_anderson",
    dimensions=dict(housing_length=.030,housing_width=.025,contact_spacing=.010,
                    max_current=45),
    color=GD,mass_kg=.010,**NYLON),
"fuse_ato_30a":_p(part_id="fuse_ato_30a",display_name="ATO保险丝座 30A",
    category="energy", manufacturer="Littelfuse", part_number="ATO Holder",
    geometry_type="fuse_holder",
    dimensions=dict(length=.035,width=.020,height=.025,fuse_type="ATO",max_current=30),
    color=BK,mass_kg=.008,**ABS),
"fuse_anl_80a":_p(part_id="fuse_anl_80a",display_name="ANL保险丝 80A",
    category="energy", manufacturer="Blue Sea Systems", part_number="ANL-80",
    geometry_type="fuse_blade_large",
    dimensions=dict(blade_length=.040,blade_width=.015,rating=80,voltage=80),
    color=YL,mass_kg=.008,**CERAMIC),
"shunt_200a": _p(part_id="shunt_200a", display_name="电流采样电阻 200A 75uOhm",
    category="energy", manufacturer="Isabellenhuette", part_number="VS-200",
    geometry_type="current_shunt",
    dimensions=dict(length=.030,width=.015,thickness=.002,resistance=75e-6,tolerance=.01),
    color=CU,mass_kg=.002,**ZINC),
}


# ════════════════════════════════════════════════════════════════════════════
#  4. 传感系统 (38种) — IMU/编码器/测距/力/环境
# ════════════════════════════════════════════════════════════════════════════
SENSORS = {
"mpu9250":    _p(part_id="mpu9250", display_name="MPU9250 IMU (9轴)",
    category="sensors", manufacturer="TDK InvenSense", part_number="MPU-9250",
    geometry_type="qfn_package",
    dimensions=dict(length=.004,width=.004,height=.001,gyro_range=2000,
                    accel_range=16,magnetometer=True),
    color=BK,mass_kg=.0005,**PCBB),
"bno055":     _p(part_id="bno055", display_name="BNO055 智能IMU (9轴+融合)",
    category="sensors", manufacturer="Bosch Sensortech", part_number="BNO055",
    geometry_type="lga28_package",
    dimensions=dict(length=.0052,width=.0032,height=.011,fusion_modes=9,euler_output=True),
    color=BK,mass_kg=.012,**PCBB),
"icm20948":  _p(part_id="icm20948", display_name="ICM-20948 6轴+磁力计",
    category="sensors", manufacturer="TDK InvenSense", part_number="ICM-20948",
    geometry_type="qfn_package",
    dimensions=dict(length=.004,width=.004,height=.001,gyro_range=2000,
                    accel_range=16,digital_motion_processor=True),
    color=BK,mass_kg=.0005,**PCBB),
"bmi270":     _p(part_id="bmi270", display_name="BMI270 6轴IMU",
    category="sensors", manufacturer="Bosch", part_number="BMI270",
    geometry_type="lga14_package",
    dimensions=dict(length=.00256,width=.00244,height=.00091,
                    gyro_range=2000,accel_range=24),
    color=BK,mass_kg=.0003,**PCBB),
"vl53l0x":    _p(part_id="vl53l0x", display_name="VL53L0X ToF激光测距",
    category="sensors", manufacturer="STMicroelectronics", part_number="VL53L0X",
    geometry_type="small_pcb_module",
    dimensions=dict(length=.0094,width=.0137,height=.001,lens_dia=.003,
                    range_max=2.0,accuracy_mm=3),
    color=BK,mass_kg=.0008,**PCBB),
"tfmini_s":   _p(part_id="tfmini_s", display_name="TFmini-S 激光雷达模组",
    category="sensors", manufacturer="Benewake", part_number="TFmini-S",
    geometry_type="lidar_module",
    dimensions=dict(length=.029,width=.021,height=.016,range_max=12,
                    range_min=.1,accuracy_cm=1),
    color=GD,mass_kg=.012,**ALU),
"ld06":       _p(part_id="ld06", display_name="LD06 360度激光雷达",
    category="sensors", manufacturer="Slamtec", part_number="LD06",
    geometry_type="lidar_cylindrical",
    dimensions=dict(diameter=.075,height=.040,range_max=12,
                    sampling_rate=4500,angular_resolution=1),
    color=BK,mass_kg=.115,**ABS),
"rplidar_a1": _p(part_id="rplidar_a1", display_name="RPLIDAR A1 激光雷达",
    category="sensors", manufacturer="Slamtec", part_number="RPLIDAR A1",
    geometry_type="lidar_disk",
    dimensions=dict(diameter=.075,height=.040,range_max=12,
                    sampling_rate=8000,angle_resolution=.225),
    color=WH,mass_kg=.198,**ABS),
"encoder_abz_1024":_p(part_id="encoder_abz_1024",display_name="增量式编码器 ABZ 1024线",
    category="sensors", manufacturer="Omron", part_number="E6B2-CWZ6C",
    geometry_type="encoder_incremental",
    dimensions=dict(body_diameter=.040,body_thickness=.025,shaft_dia=.006,
                    ppr=1024,max_rpm=6000),
    color=BK,mass_kg=.035,**ABS),
"encoder_abs_19bit":_p(part_id="encoder_abs_19bit",display_name="绝对值多圈编码器 19位",
    category="sensors", manufacturer="Tamagawa", part_number="TS5208N560",
    geometry_type="encoder_absolute",
    dimensions=dict(body_diameter=.058,body_thickness=.030,shaft_dia=.010,
                    resolution=19,max_rpm=3000),
    color=BK,mass_kg=.085,**ALU),
"loadcell_50kg":_p(part_id="loadcell_50kg",display_name="称重传感器 50kg",
    category="sensors", manufacturer="通用", part_number="Load Cell 50kg",
    geometry_type="load_cell_aluminum",
    dimensions=dict(length=.125,width=.013,height=.025,capacity=50,
                    excitation_voltage=10,sensitivity=2.0),
    color=AU,mass_kg=.025,**ALU),
"hx711_amp":  _p(part_id="hx711_amp", display_name="HX711 称重放大模块",
    category="sensors", manufacturer="Avia Semiconductor", part_number="HX711",
    geometry_type="small_pcb_module",
    dimensions=dict(length=.015,width=.011,height=.002,gain=128,channels=2),
    color=RD,mass_kg=.001,**PCBB),
"sht31":      _p(part_id="sht31", display_name="SHT31 温湿度传感器",
    category="sensors", manufacturer="Sensirion", part_number="SHT31-D",
    geometry_type="dfn_package",
    dimensions=dict(length=.0024,width=.0024,height=.0008,
                    temp_accuracy=.2,humidity_accuracy=.02),
    color=BK,mass_kg=.0002,**PCBB),
"bme280":     _p(part_id="bme280", display_name="BME280 环境传感器(温湿气压)",
    category="sensors", manufacturer="Bosch", part_number="BME280",
    geometry_type="lga8_package",
    dimensions=dict(length=.0025,width=.0025,height=.00091,
                    pressure_range=(300,1100)),
    color=BK,mass_kg=.0003,**PCBB),
"as5600":     _p(part_id="as5600", display_name="AS5600 磁性角度编码器",
    category="sensors", manufacturer="AMS", part_number="AS5600",
    geometry_type="so8_package",
    dimensions=dict(length=.005,width=.004,height=.00165,resolution=12),
    color=BK,mass_kg=.0005,**PCBB),
"acs712_20a": _p(part_id="acs712_20a", display_name="ACS712 电流传感器 +/-20A",
    category="sensors", manufacturer="Allegro", part_number="ACS712ELCTR-20A",
    geometry_type="so8_package",
    dimensions=dict(length=.005,width=.006,height=.0015,sensitivity=100),
    color=BK,mass_kg=.001,**PCBB),
"ina219":     _p(part_id="ina219", display_name="INA219 双向电流/功率监测",
    category="sensors", manufacturer="TI", part_number="INA219",
    geometry_type="sot23_8",
    dimensions=dict(length=.0029,width=.0016,height=.0011,
                    shunt_range=(0,32),bus_voltage_max=26),
    color=BK,mass_kg=.0002,**PCBB),
"hc_sr04":    _p(part_id="hc_sr04", display_name="HC-SR04 超声波测距",
    category="sensors", manufacturer="Cytron", part_number="HC-SR04",
    geometry_type="ultrasonic_sensor",
    dimensions=dict(length=.045,width=.020,height=.015,
                    range_min=.02,range_max=4.0,angle=15),
    color=GM,mass_kg=.008,**ABS),
"jsn_sr04t":  _p(part_id="jsn_sr04t", display_name="JSN-SR04T 防水超声波",
    category="sensors", manufacturer="通用", part_number="JSN-SR04T",
    geometry_type="ultrasonic_waterproof",
    dimensions=dict(diameter=.016,length=.022,range_min=.01,range_max=4.5),
    color=GM,mass_kg=.005,**ABS),
"max30102":   _p(part_id="max30102", display_name="MAX30102 心率血氧传感器",
    category="sensors", manufacturer="Maxim Integrated", part_number="MAX30102",
    geometry_type="qfn_package",
    dimensions=dict(length=.0054,width=.0033,height=.0009),
    color=BK,mass_kg=.0004,**PCBB),
"ms5803":     _p(part_id="ms5803", display_name="MS5803 深度压力传感器",
    category="sensors", manufacturer="TE Connectivity", part_number="MS5803-14BA",
    geometry_type="pressure_sensor_can",
    dimensions=dict(diameter=.0065,height=.0049,depth_range=(-10,110)),
    color=GD,mass_kg=.0002,**STL),
"lis3mdl":    _p(part_id="lis3mdl", display_name="LIS3MDL 三轴磁力计",
    category="sensors", manufacturer="STMicroelectronics", part_number="LIS3MDL",
    geometry_type="lga12_package",
    dimensions=dict(length=.0025,width=.0025,height=.0007,range=16),
    color=BK,mass_kg=.0002,**PCBB),
"encoder_hollow_17bit":_p(part_id="encoder_hollow_17bit",display_name="空心绝对值编码器 17位",
    category="sensors", manufacturer="Heidenhain", part_number="ECI 1118",
    geometry_type="encoder_hollow",
    dimensions=dict(od=.058,id=.020,thickness=.030,resolution=17),
    color=GD,mass_kg=.120,**ALU),
"loadcell_5kg":_p(part_id="loadcell_5kg",display_name="称重传感器 5kg",
    category="sensors", manufacturer="通用", part_number="Load Cell 5kg",
    geometry_type="load_cell_mini",
    dimensions=dict(length=.035,width=.013,height=.012,capacity=5,
                    excitation_voltage=5,sensitivity=1.0),
    color=AU,mass_kg=.003,**ALU),
"tof_10120":  _p(part_id="tof_10120", display_name="ToF激光测距 10120 (1.8m)",
    category="sensors", manufacturer="Benewake", part_number="TF01-S",
    geometry_type="lidar_module_long",
    dimensions=dict(length=.045,width=.020,height=.020,range_max=1.8,
                    accuracy_cm=1),
    color=GD,mass_kg=.015,**ALU),
"dht22":      _p(part_id="dht22", display_name="DHT22 温湿度传感器",
    category="sensors", manufacturer="Aosong", part_number="DHT22",
    geometry_type="sensor_with_grill",
    dimensions=dict(length=.015,width=.025,height=.005,
                    temp_range=(-40,80),humidity_range=(0,100)),
    color=GL,mass_kg=.003,**ABS),
"pir_motion":  _p(part_id="pir_motion", display_name="HC-SR501 PIR人体感应",
    category="sensors", manufacturer="通用", part_number="HC-SR501",
    geometry_type="sensor_pir",
    dimensions=dict(length=.032,width=.020,height=.024,detect_range=7,detect_angle=110),
    color=WH,mass_kg=.010,**ABS),
"ir_obstacle": _p(part_id="ir_obstacle", display_name="红外避障传感器",
    category="sensors", manufacturer="通用", part_number="IR Obstacle",
    geometry_type="sensor_ir_pair",
    dimensions=dict(length=.038,width=.012,height=.012,detect_range=.03),
    color=BK,mass_kg=.002,**ABS),
"tcs34725":  _p(part_id="tcs34725", display_name="TCS34725 RGB颜色传感器",
    category="sensors", manufacturer="AMS", part_number="TCS34725",
    geometry_type="qfn_package",
    dimensions=dict(length=.0028,width=.0024,height=.001,resolution=12),
    color=BK,mass_kg=.0003,**PCBB),
}


# ════════════════════════════════════════════════════════════════════════════
#  5. 控制系统 (22种)
# ════════════════════════════════════════════════════════════════════════════
CONTROLLERS = {
"raspberry_pi5": _p(part_id="raspberry_pi5", display_name="Raspberry Pi 5 主控",
    category="controllers", manufacturer="Raspberry Pi Foundation", part_number="Pi 5 8GB",
    geometry_type="pcb_board",
    dimensions=dict(length=.085,width=.056,usb_height=.012,
                    gpio_header_height=.010,ethernet_height=.010),
    color=GN,mass_kg=.046,voltage_v=5,current_a=3,**PCBG),
"stm32h743": _p(part_id="stm32h743", display_name="STM32H743 开发板",
    category="controllers", manufacturer="STMicroelectronics", part_number="NUCLEO-H743ZI",
    geometry_type="pcb_board_large",
    dimensions=dict(length=.135,width=.070,usb_height=.012,
                    gpio_header_height=.010,ethernet_height=.010),
    color=GN,mass_kg=.055,voltage_v=3.3,current_a=.5,**PCBG),
"teensy41":   _p(part_id="teensy41", display_name="Teensy 4.1 高性能MCU",
    category="controllers", manufacturer="PJRC", part_number="Teensy 4.1",
    geometry_type="small_pcb_module",
    dimensions=dict(length=.061,width=.018,height=.004,core="Cortex-M7",sram=1024),
    color=RD,mass_kg=.012,voltage_v=3.3,current_a=.25,**PCBB),
"arduino_mega":_p(part_id="arduino_mega", display_name="Arduino Mega 2560",
    category="controllers", manufacturer="Arduino", part_number="Mega 2560 Rev3",
    geometry_type="pcb_board",
    dimensions=dict(length=.101,width=.053,usb_height=.012,gpio_header_height=.010),
    color=GN,mass_kg=.037,voltage_v=5,current_a=.15,**PCBG),
"esp32_dev":   _p(part_id="esp32_dev", display_name="ESP32 WROOM 开发板",
    category="controllers", manufacturer="Espressif", part_number="ESP32-DevKitC",
    geometry_type="small_pcb_module",
    dimensions=dict(length=.055,width=.028,height=.003,wifi_ble=True,dual_core=240),
    color=GM,mass_kg=.010,voltage_v=3.3,current_a=.08,**PCBB),
"can_transceiver_tja1050":_p(part_id="can_transceiver_tja1050",display_name="CAN收发器 TJA1050T",
    category="controllers", manufacturer="NXP", part_number="TJA1050T",
    geometry_type="so8_package",
    dimensions=dict(length=.005,width=.004,height=.00165,speed=1e6),
    color=BK,mass_kg=.0005,**PCBB),
"tb6612fng":  _p(part_id="tb6612fng", display_name="TB6612FNG 双路电机驱动",
    category="controllers", manufacturer="Toshiba", part_number="TB6612FNG",
    geometry_type="ssop24_package",
    dimensions=dict(length=.006,width=.0045,height=.0017,channels=2,peak_current=3.2),
    color=BK,mass_kg=.001,**PCBB),
"a4988":      _p(part_id="a4988", display_name="A4988 步进电机驱动",
    category="controllers", manufacturer="Allegro", part_number="A4988",
    geometry_type="qfn_package",
    dimensions=dict(length=.005,width=.005,height=.001,microsteps=16,max_current=2.0),
    color=BK,mass_kg=.002,**PCBB),
"l298n":      _p(part_id="l298n", display_name="L298N 双H桥电机驱动模块",
    category="controllers", manufacturer="ST", part_number="L298N Module",
    geometry_type="dc_dc_enclosed",
    dimensions=dict(length=.055,width=.043,height=.030,channels=2,peak_current=3.0),
    color=BK,mass_kg=.030,**ALU),
"drv8871":    _p(part_id="drv8871", display_name="DRV8871 单路电机驱动",
    category="controllers", manufacturer="TI", part_number="DRV8871",
    geometry_type="so8_package",
    dimensions=dict(length=.005,width=.006,height=.00165,peak_current=3.6),
    color=BK,mass_kg=.001,**PCBB),
"pca9685":    _p(part_id="pca9685", display_name="PCA9685 16路PWM伺服驱动",
    category="controllers", manufacturer="NXP", part_number="PCA9685",
    geometry_type="qfn_package",
    dimensions=dict(length=.005,width=.005,height=.001,channels=16,resolution=12),
    color=BK,mass_kg=.0005,**PCBB),
"usb_hub_4port":_p(part_id="usb_hub_4port", display_name="USB 3.0 Hub 4口",
    category="controllers", manufacturer="Anker", part_number="AH230",
    geometry_type="box_compact",
    dimensions=dict(length=.075,width=.045,height=.015,ports=4),
    color=BK,mass_kg=.035,**ABS),
"can_hub_4ch":_p(part_id="can_hub_4ch", display_name="CAN HUB 4口分线器",
    category="controllers", manufacturer="通用", part_number="CAN-HUB-4",
    geometry_type="box_compact",
    dimensions=dict(length=.055,width=.035,height=.020,ports=4),
    color=GD,mass_kg=.025,**ALU),
"voltage_reg_7v":_p(part_id="voltage_reg_7v", display_name="L7807CV 7V稳压模块",
    category="controllers", manufacturer="ST", part_number="L7807CV",
    geometry_type="to220_package",
    dimensions=dict(length=.010,width=.015,height=.009,output=7,current_max=1.5),
    color=GD,mass_kg=.002,**ZINC),
"relay_5v_2ch":_p(part_id="relay_5v_2ch", display_name="5V双路继电器模块",
    category="controllers", manufacturer="Songle", part_number="SRD-05VDC",
    geometry_type="box_compact",
    dimensions=dict(length=.040,width=.025,height=.020,channels=2,coil_voltage=5),
    color=GL,mass_kg=.020,**ABS),
"opto_isolator":_p(part_id="opto_isolator", display_name="光耦隔离模块 4通道",
    category="controllers", manufacturer="Toshiba", part_number="TLP281-4",
    geometry_type="so16_package",
    dimensions=dict(length=.005,width=.005,height=.002,channels=4),
    color=BK,mass_kg=.002,**PCBB),
"rs485_module":_p(part_id="rs485_module", display_name="MAX485 RS-485收发模块",
    category="controllers", manufacturer="Maxim", part_number="MAX485",
    geometry_type="so8_package",
    dimensions=dict(length=.005,width=.004,height=.00165,speed=2.5e6),
    color=BK,mass_kg=.001,**PCBB),
"e_stop_button":_p(part_id="e_stop_button", display_name="急停按钮 O22 红色蘑菇头",
    category="controllers", manufacturer="Schneider", part_number="XB4-BT42",
    geometry_type="button_mushroom",
    dimensions=dict(mushroom_dia=.036,body_diameter=.022,body_depth=.040,contacts="NC"),
    color=RD,mass_kg=.035,**ABS),
"limit_switch":_p(part_id="limit_switch", display_name="微动开关 限位器",
    category="controllers", manufacturer="Omron", part_number="D2F-FL",
    geometry_type="micro_switch",
    dimensions=dict(length=.0125,width=.0063,height=.0125,actuation_force=1.47),
    color=GD,mass_kg=.002,**ABS),
"joystick_thumb":_p(part_id="joystick_thumb", display_name="拇指摇杆模块 KY-023",
    category="controllers", manufacturer="通用", part_number="KY-023",
    geometry_type="joystick_module",
    dimensions=dict(length=.040,width=.030,height=.035,axes=2,button=True),
    color=GM,mass_kg=.015,**ABS),
"potentiometer_10k":_p(part_id="potentiometer_10k", display_name="旋转电位器 10kOhm",
    category="controllers", manufacturer="Bourns", part_number="PTV09A",
    geometry_type="potentiometer_rotary",
    dimensions=dict(body_diameter=.016,body_depth=.025,shaft_dia=.006,
                    shaft_length=.020,resistance=10e3,rotation=300),
    color=GD,mass_kg=.012,**ABS),
"slider_pot_10k":_p(part_id="slider_pot_10k", display_name="滑动电位器 10kOhm",
    category="controllers", manufacturer="Bourns", part_number="PTA6043",
    geometry_type="slider_pot",
    dimensions=dict(length=.060,width=.010,height=.017,travel=.045,resistance=10e3),
    color=GM,mass_kg=.008,**ABS),
}


# ════════════════════════════════════════════════════════════════════════════
#  6. 连接件/结构件 (45种)
# ════════════════════════════════════════════════════════════════════════════
CONNECTORS = {
"flange_o60": _p(part_id="flange_o60", display_name="安装法兰 O60 标准型",
    category="connectors", manufacturer="通用", part_number="FLG-60-4H",
    geometry_type="ring_with_holes",
    dimensions=dict(outer_diameter=.060,inner_diameter=.020,thickness=.005,
                    bolt_circle_diameter=.048,bolt_count=4,bolt_diameter=.004),
    color=GL,mass_kg=.025,**ALU),
"bearing_6000zz":_p(part_id="bearing_6000zz", display_name="深沟球轴承 6000ZZ",
    category="connectors", manufacturer="SKF", part_number="6000-2Z",
    geometry_type="bearing_assembly",
    dimensions=dict(outer_diameter=.026,inner_diameter=.010,width=.008,
                    ball_diameter=.004,ball_count=7),
    color=GD,mass_kg=.019,**STL),
"bearing_608zz":_p(part_id="bearing_608zz", display_name="深沟球轴承 608ZZ",
    category="connectors", manufacturer="SKF", part_number="608-2Z",
    geometry_type="bearing_assembly",
    dimensions=dict(outer_diameter=.022,inner_diameter=.008,width=.007,
                    ball_diameter=.0035,ball_count=7),
    color=GD,mass_kg=.012,**STL),
"bearing_6200zz":_p(part_id="bearing_6200zz", display_name="深沟球轴承 6200ZZ",
    category="connectors", manufacturer="SKF", part_number="6200-2Z",
    geometry_type="bearing_assembly",
    dimensions=dict(outer_diameter=.030,inner_diameter=.010,width=.009,
                    ball_diameter=.0045,ball_count=8),
    color=GD,mass_kg=.032,**STL),
"thrust_bearing_51100":_p(part_id="thrust_bearing_51100", display_name="推力球轴承 51100",
    category="connectors", manufacturer="SKF", part_number="51100",
    geometry_type="bearing_thrust",
    dimensions=dict(outer_diameter=.026,inner_diameter=.010,width=.009,
                    ball_diameter=.003,ball_count=16),
    color=GD,mass_kg=.020,**STL),
"angular_contact_7000":_p(part_id="angular_contact_7000", display_name="角接触球轴承 7000C",
    category="connectors", manufacturer="NSK", part_number="7000CT",
    geometry_type="bearing_angular",
    dimensions=dict(outer_diameter=.026,inner_diameter=.010,width=.008,contact_angle=15),
    color=GD,mass_kg=.019,**STL),
"rigid_coupling_o12_l25":_p(part_id="rigid_coupling_o12_l25",display_name="刚性联轴器 O12 L25",
    category="connectors", manufacturer="通用", part_number="RC-12-25",
    geometry_type="coupling_rigid",
    dimensions=dict(outer_diameter=.012,total_length=.025,bore=.006,set_screw=2),
    color=GL,mass_kg=.010,**ALU),
"clamp_collar_o8":_p(part_id="clamp_collar_o8", display_name="轴夹紧环 O8",
    category="connectors", manufacturer="Ruland", part_number="MSC-8-SS",
    geometry_type="ring_split",
    dimensions=dict(outer_diameter=.018,inner_diameter=.008,thickness=.008,
                    bolt_count=1,bolt_diameter=.003),
    color=GL,mass_kg=.008,**SUS),
"quick_release_pin_o6":_p(part_id="quick_release_pin_o6", display_name="快拆销 O6 L30",
    category="connectors", manufacturer="通用", part_number="QRP-6-30",
    geometry_type="pin_with_ball",
    dimensions=dict(diameter=.006,length=.030,ball_diameter=.004),
    color=GL,mass_kg=.004,**STL),
"aluminum_profile_2020_100":_p(part_id="aluminum_profile_2020_100",display_name="铝型材 2020 L=100mm",
    category="connectors", manufacturer="Bosch Rexroth", part_number="20x20 L100",
    geometry_type="extrusion_profile",
    dimensions=dict(size=.020,length=.100,slot=6),
    color=GL,mass_kg=.075,**ALU),
"aluminum_profile_2020_300":_p(part_id="aluminum_profile_2020_300",display_name="铝型材 2020 L=300mm",
    category="connectors", manufacturer="Bosch Rexroth", part_number="20x20 L300",
    geometry_type="extrusion_profile",
    dimensions=dict(size=.020,length=.300,slot=6),
    color=GL,mass_kg=.225,**ALU),
"aluminum_profile_3030_200":_p(part_id="aluminum_profile_3030_200",display_name="铝型材 3030 L=200mm",
    category="connectors", manufacturer="Bosch Rexroth", part_number="30x30 L200",
    geometry_type="extrusion_profile",
    dimensions=dict(size=.030,length=.200,slot=8),
    color=GL,mass_kg=.320,**ALU),
"carbon_tube_o16_l200":_p(part_id="carbon_tube_o16_l200",display_name="碳纤维管 O16x14 L=200mm",
    category="connectors", manufacturer="通用", part_number="CFT-16-14-200",
    geometry_type="tube_hollow",
    dimensions=dict(outer_diameter=.016,length=.200,inner_diameter=.014),
    color=BK,mass_kg=.028,**ABS),
"carbon_tube_o25_l300":_p(part_id="carbon_tube_o25_l300",display_name="碳纤维管 O25x22 L=300mm",
    category="connectors", manufacturer="通用", part_number="CFT-25-22-300",
    geometry_type="tube_hollow",
    dimensions=dict(outer_diameter=.025,length=.300,inner_diameter=.022),
    color=BK,mass_kg=.085,**ABS),
"steel_plate_100":_p(part_id="steel_plate_100", display_name="钢板 100x100x3mm",
    category="connectors", manufacturer="通用", part_number="SP-100-100-3",
    geometry_type="flat_plate",
    dimensions=dict(length=.100,width=.100,thickness=.003),
    color=GD,mass_kg=.235,**STL),
"steel_plate_150":_p(part_id="steel_plate_150", display_name="钢板 150x100x5mm",
    category="connectors", manufacturer="通用", part_number="SP-150-100-5",
    geometry_type="flat_plate",
    dimensions=dict(length=.150,width=.100,thickness=.005),
    color=GD,mass_kg=.588,**STL),
"compression_spring_o10_l30":_p(part_id="compression_spring_o10_l30",display_name="压缩弹簧 O10 L30",
    category="connectors", manufacturer="MISUMI", part_number="WR10-30",
    geometry_type="helix_spring",
    dimensions=dict(outer_diameter=.010,free_length=.030,wire_diameter=.0012,
                    active_coils=8,spring_rate=3.5),
    color=GL,mass_kg=.004,**STL),
"compression_spring_o20_l50":_p(part_id="compression_spring_o20_l50",display_name="压缩弹簧 O20 L50",
    category="connectors", manufacturer="MISUMI", part_number="WR20-50",
    geometry_type="helix_spring",
    dimensions=dict(outer_diameter=.020,free_length=.050,wire_diameter=.002,
                    active_coils=10,spring_rate=8.0),
    color=GL,mass_kg=.015,**STL),
"aluminum_hollow_tube_o20":_p(part_id="aluminum_hollow_tube_o20",display_name="铝合金空心管 O20x17 L150mm",
    category="connectors", manufacturer="通用", part_number="ALT-20-17-150",
    geometry_type="tube_hollow",
    dimensions=dict(outer_diameter=.020,length=.150,inner_diameter=.017),
    color=GL,mass_kg=.050,**ALU),
"hemisphere_foot_o30":_p(part_id="hemisphere_foot_o30", display_name="半球形脚垫 O30 橡胶",
    category="connectors", manufacturer="MISUMI", part_number="RSF-30",
    geometry_type="sphere_cap",
    dimensions=dict(diameter=.030,height=.015,mount_hole_dia=.008),
    color=BK,mass_kg=.012,**RUBBER),
"sliding_block_2020":_p(part_id="sliding_block_2020", display_name="2020型材滑动螺母",
    category="connectors", manufacturer="MISUMI", part_number="HNTT5-5",
    geometry_type="aluminum_block",
    dimensions=dict(length=.008,width=.006,height=.004,hole_dia=.004),
    color=GL,mass_kg=.001,**ALU),
"corner_bracket_2020":_p(part_id="corner_bracket_2020", display_name="2020型材角码 L型",
    category="connectors", manufacturer="MISUMI", part_number="HBLFSN5",
    geometry_type="l_bracket",
    dimensions=dict(arm_length=.030,arm_width=.020,thickness=.004,
                    slot_count=1,slot_spacing=.020),
    color=GL,mass_kg=.015,**ALU),
"t_nut_m4":   _p(part_id="t_nut_m4", display_name="T型螺母 M4 2020型材用",
    category="connectors", manufacturer="MISUMI", part_number="HNTT5-4",
    geometry_type="aluminum_block",
    dimensions=dict(length=.010,width=.006,height=.004,hole_dia=.004),
    color=GL,mass_kg=.0015,**ALU),
}


# ════════════════════════════════════════════════════════════════════════════
#  合并所有零件 & 导出函数
# ════════════════════════════════════════════════════════════════════════════

def get_all_part_specs():
    all_parts = {}
    for cat in [ACTUATORS, TRANSMISSION, ENERGY, SENSORS, CONTROLLERS, CONNECTORS]:
        all_parts.update(cat)
    return all_parts


if __name__ == "__main__":
    parts = get_all_part_specs()
    cats = [("执行器", ACTUATORS), ("传动系统", TRANSMISSION),
            ("能源系统", ENERGY), ("传感系统", SENSORS),
            ("控制系统", CONTROLLERS), ("连接件", CONNECTORS)]
    print("=" * 50)
    print("  V8 零件规格库 v2")
    print("=" * 50)
    total = 0
    for name, cat in cats:
        n = len(cat)
        total += n
        print(f"  {name:12s} : {n:3d} 种")
    print(f"  {'─' * 30}")
    print(f"  总计          : {total:3d} 种")
    print("=" * 50)