"""
G-code 生成器 — 支持 Marlin / Klipper / RepRap 三种方言

功能:
  - 多挤出机支持 (T0/T1)
  - E 值精确计算 (体积 → 丝材长度)
  - 回抽/回填控制
  - 圆弧拟合 (G2/G3)
  - start/end gcode 模板
"""

import math
from typing import Dict, List, Optional

import numpy as np

from forgecraft.cam.types import GCodeSettings, LayerToolpath, PathSegment, BuildPlateLayout

__all__ = ["GCodeWriter"]

# 挤出截面 bulge 修正系数
_BULGE_FACTOR = 1.0


class GCodeWriter:
    """G-code 写入器

    Usage:
        writer = GCodeWriter(settings)
        gcode = writer.write_all(toolpaths, layout)
    """

    def __init__(self, settings: GCodeSettings = None):
        self.settings = settings or GCodeSettings()
        self._current_pos = np.array([0.0, 0.0, 0.0])
        self._current_e = 0.0
        self._current_extruder = 0
        self._is_retracted = False
        self._lines: List[str] = []

    # ═══════════════════════════════════════════════
    # 主入口
    # ═══════════════════════════════════════════════

    def write_all(
        self,
        toolpaths: List[LayerToolpath],
        layout: Optional[BuildPlateLayout] = None,
        part_name: str = "ForgeCraft_Print",
    ) -> str:
        """生成完整 G-code"""
        self._lines = []
        self._current_e = 0.0
        self._current_extruder = 0
        self._is_retracted = False

        s = self.settings

        # Header
        self._write_header(part_name)

        # Start gcode
        self._write_start_gcode()

        # 逐层
        for layer in toolpaths:
            self._write_layer_comment(layer.z, layer.height)

            # 外壳
            for seg in layer.perimeters:
                self._write_segment(seg, s.print_speed)

            # 填充
            for seg in layer.infill:
                self._write_segment(seg, s.print_speed)

            # 顶/底层
            for seg in layer.skin:
                self._write_segment(seg, s.print_speed)

            # 桥接
            for seg in layer.bridges:
                self._write_segment(seg, s.print_speed * 0.8)

            # 空驶
            for seg in layer.travel:
                self._write_travel(seg)

        # End gcode
        self._write_end_gcode()

        return "\n".join(self._lines)

    # ═══════════════════════════════════════════════
    # Header / Footer
    # ═══════════════════════════════════════════════

    def _write_header(self, name: str):
        s = self.settings
        self._lines.append(f"; Generated by ForgeCraft CAM")
        self._lines.append(f"; Part: {name}")
        self._lines.append(f"; Dialect: {s.dialect}")
        self._lines.append(f"; Nozzle: {s.nozzle_diameter}mm  Layer: {s.layer_height}mm")
        self._lines.append(f"; Filament: {s.filament_diameter}mm")
        self._lines.append(f"; Extruders: {s.extruder_count}")
        self._lines.append("")

    def _write_start_gcode(self):
        s = self.settings
        bed = s.bed_temp
        nozzle = s.nozzle_temp

        if s.dialect == "klipper":
            self._lines.extend([
                "START_PRINT",
                f"M104 S{nozzle}  ; Set extruder temp",
                f"M140 S{bed}    ; Set bed temp",
                "M109 S{nozzle}  ; Wait for extruder",
                "M190 S{bed}     ; Wait for bed",
                "G28             ; Home all axes",
                "G92 E0          ; Reset extruder",
                "G1 Z2.0 F3000   ; Move Z up",
            ])
        else:  # marlin / reprap
            self._lines.extend([
                f"M140 S{bed}    ; Set bed temp",
                f"M104 S{nozzle} ; Set extruder temp",
                f"M190 S{bed}    ; Wait for bed",
                f"M109 S{nozzle} ; Wait for extruder",
                "G28             ; Home all axes",
                "G92 E0          ; Reset extruder",
                "G1 Z2.0 F3000   ; Move Z up",
                "; Prime line",
                "G1 X10.0 Y0.0 Z0.3 F1500",
                "G1 X60.0 E3.0 F500",
                "G1 X100.0 E5.0 F500",
                "G92 E0",
            ])

        self._current_pos = np.array([0.0, 0.0, 2.0])

    def _write_end_gcode(self):
        s = self.settings
        if s.dialect == "klipper":
            self._lines.extend([
                "END_PRINT",
                "M104 S0         ; Turn off extruder",
                "M140 S0         ; Turn off bed",
                "G1 Z10 F3000    ; Move Z up",
                "M84             ; Disable motors",
            ])
        else:
            self._lines.extend([
                "M104 S0         ; Turn off extruder",
                "M140 S0         ; Turn off bed",
                "G1 Z10 F3000    ; Move Z up",
                "G28 X0 Y0       ; Home XY",
                "M84             ; Disable motors",
            ])

    def _write_layer_comment(self, z: float, height: float):
        self._lines.append(f"")
        self._lines.append(f"; LAYER at Z={z:.3f}  height={height:.3f}")

    # ═══════════════════════════════════════════════
    # 运动指令
    # ═══════════════════════════════════════════════

    def _write_segment(self, seg: PathSegment, feedrate: float):
        """写入挤出/空驶路径段"""
        if len(seg.points) < 2:
            return

        s = self.settings
        f = seg.feedrate if seg.feedrate > 0 else feedrate

        if seg.is_extrude:
            # 如果之前回抽了，先回填
            if self._is_retracted:
                self._write_unretract()

            # 挤出段
            for i in range(1, len(seg.points)):
                pt = seg.points[i]
                dist = np.linalg.norm(pt - self._current_pos[:2])
                if dist < 1e-6:
                    continue

                # E 值计算
                e_add = self._compute_e(dist)
                self._current_e += e_add

                self._lines.append(
                    f"G1 X{pt[0]:.3f} Y{pt[1]:.3f} E{self._current_e:.5f} F{int(f * 60)}"
                )
                self._current_pos[:2] = pt
        else:
            # 空驶
            self._write_rapid_move(seg.points[-1], f)

    def _write_travel(self, seg: PathSegment):
        """空驶移动"""
        if len(seg.points) < 2:
            return

        s = self.settings

        if not self._is_retracted:
            self._write_retract()

        for i in range(1, len(seg.points)):
            pt = seg.points[i]
            if s.dialect == "klipper":
                self._lines.append(
                    f"G0 X{pt[0]:.3f} Y{pt[1]:.3f} F{int(s.travel_speed * 60)}"
                )
            else:
                self._lines.append(
                    f"G0 X{pt[0]:.3f} Y{pt[1]:.3f} F{int(s.travel_speed * 60)}"
                )
            self._current_pos[:2] = pt

    def _write_rapid_move(self, target: np.ndarray, feedrate: float):
        """快速移动到目标点"""
        s = self.settings
        dist = np.linalg.norm(target - self._current_pos[:2])
        if dist < 0.5:
            return

        if self._is_retracted:
            self._write_unretract()

        self._lines.append(
            f"G0 X{target[0]:.3f} Y{target[1]:.3f} F{int(s.travel_speed * 60)}"
        )
        self._current_pos[:2] = target

    def _write_retract(self):
        s = self.settings
        self._current_e -= s.retract_distance
        self._lines.append(
            f"G1 E{self._current_e:.5f} F{int(s.retract_speed * 60)} ; retract"
        )
        self._is_retracted = True

    def _write_unretract(self):
        s = self.settings
        self._current_e += s.retract_distance
        self._lines.append(
            f"G1 E{self._current_e:.5f} F{int(s.unretract_speed * 60)} ; unretract"
        )
        self._is_retracted = False

    def _compute_e(self, distance_mm: float) -> float:
        """计算 E 增量

        体积 = distance × extrusion_width × layer_height × bulge
        丝材截面 = π × (d/2)²
        E = 体积 / 丝材截面
        """
        s = self.settings
        volume = distance_mm * s.extrusion_width * s.layer_height * _BULGE_FACTOR
        filament_area = math.pi * (s.filament_diameter / 2.0) ** 2
        return volume / filament_area

    # ═══════════════════════════════════════════════
    # 多挤出机
    # ═══════════════════════════════════════════════

    def write_tool_change(self, extruder_id: int):
        """切换挤出机"""
        if extruder_id == self._current_extruder:
            return

        self._write_retract()
        self._lines.append(f"T{extruder_id}  ; tool change")
        self._current_extruder = extruder_id
        self._current_e = 0.0
        self._is_retracted = False
        self._lines.append("G92 E0  ; reset extruder")

    # ═══════════════════════════════════════════════
    # 圆弧拟合
    # ═══════════════════════════════════════════════

    def write_arc(
        self, center: np.ndarray, end: np.ndarray, radius: float, clockwise: bool = True
    ):
        """写入 G2/G3 圆弧指令"""
        s = self.settings
        if s.dialect == "reprap":
            # RepRap 不支持 G2/G3，用线段逼近
            self._approximate_arc(center, end, radius, clockwise)
            return

        cmd = "G2" if clockwise else "G3"
        # I, J = center relative to start
        i = center[0] - self._current_pos[0]
        j = center[1] - self._current_pos[1]

        self._lines.append(
            f"{cmd} X{end[0]:.3f} Y{end[1]:.3f} I{i:.3f} J{j:.3f} E{self._current_e:.5f}"
        )
        self._current_pos[:2] = end

    def _approximate_arc(
        self, center: np.ndarray, end: np.ndarray, radius: float, clockwise: bool
    ):
        """线段近似圆弧"""
        start = self._current_pos[:2].copy()
        start_angle = math.atan2(start[1] - center[1], start[0] - center[0])
        end_angle = math.atan2(end[1] - center[1], end[0] - center[0])

        if clockwise:
            if end_angle > start_angle:
                end_angle -= 2 * math.pi
            angles = np.linspace(start_angle, end_angle, 20)
        else:
            if end_angle < start_angle:
                end_angle += 2 * math.pi
            angles = np.linspace(start_angle, end_angle, 20)

        s = self.settings
        for a in angles[1:]:
            pt = center + radius * np.array([math.cos(a), math.sin(a)])
            dist = np.linalg.norm(pt - self._current_pos[:2])
            e_add = self._compute_e(dist)
            self._current_e += e_add
            self._lines.append(
                f"G1 X{pt[0]:.3f} Y{pt[1]:.3f} E{self._current_e:.5f}"
            )
            self._current_pos[:2] = pt
